init:
  '!gcpCredentials': $params.authWith
  appPath: /tmp/replay
  functionName: StorageReplay
  gcp: ${secrets.$gcpCredentials}
  serviceAccount: $gcp.ClientEmail
  prefix: $Replace(${gcp.ProjectID},'-','_')
  replayBucket: ${prefix}_replay
  triggerBucket: ${prefix}_trigger

pipeline:

  deploy:
    checkOut:
      action: vc/git:checkout
      Origin:
        URL: https://github.com/viant/smirror.git
      Dest:
        URL: ${appPath}

    package:
      action: exec:run
      target: $target
      checkError: true
      commands:
        - cd ${appPath}
        - unset GOPATH
        - export GO111MODULE=on
        - rm -rf vendor
        - go mod vendor

    upload:
      action: gcp/cloudfunctions:deploy
      credentials: $gcpCredentials
      public: true
      '@name': $functionName
      entryPoint: $functionName
      runtime: go111
      availableMemoryMb: 256
      timeout: 540s
      serviceAccountEmail: $serviceAccount
      environmentVariables:
        LOGGING: 'true'
      source:
        URL: ${appPath}/
      sleepTimeMs: 5000

  schedule:
    action: gcp/cloudscheduler:deploy
    credentials: $gcpCredentials
    init:
      body: $Cat('request.json')
    name: Replay
    schedule: 0 * * * *
    body: $body
    httpTarget:
      headers:
        User-Agent: Google-Cloud-Scheduler
      httpMethod: POST
      uri: https://us-central1-${gcp.ProjectID}.cloudfunctions.net/StorageReplay
