init:
  appPath: $Pwd(../..)
  gsTriggerBucket: e2etst
  codeZip: ${appPath}/aws/smirror.zip
  functionName: E2etstMirror
  privilegePolicy: privilege-policy.json
  awsCredentials: aws-e2e

pipeline:

  package:
    action: exec:run
    target: $target
    checkError: true
    commands:
      - unset GOPATH
      - cd ${appPath}
      - export GO111MODULE=on
      - go mod vendor
      - export GOOS=linux
      - export GOARCH=amd64
      - cd aws
      - go build -o smirror
      - zip -j smirror.zip smirror

  deployLambda:
    action: aws/lambda:deploy
    credentials: $awsCredentials
    functionname: $functionName
    runtime:  go1.x
    handler: smirror
    timeout: 360
    environment:
      variables:
        LOGGING: 'true'
        CONFIG: s3://${s3TriggerBucket}/e2e-mirror/config/mirror.json
    code:
      zipfile: $LoadBinary(${codeZip})
    rolename: lambda-${functionName}-executor
    define:
      - policyname: kms-${functionName}-role
        policydocument: $Cat('${privilegePolicy}')
    attach:
      - policyarn: arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  setTrigger:
    action: aws/s3:setupBucketNotification
    sleepTimeMs: 20000
    bucket: ${s3TriggerBucket}
    lambdaFunctionConfigurations:
      - functionName: $functionName
        id: ObjectCreatedEvents
        events:
          - s3:ObjectCreated:*
        filter:
          prefix:
            - data
