init:

  '!gcpCredentials': $params.authWith
  '!topic': $params.topic


  gcp: ${secrets.$gcpCredentials}
  gcpProject: $gcp.ProjectID
  serviceAccount: $gcp.ClientEmail
  bucketPrefix: $Replace($gcpProject,'-','_')
  appPath: /tmp/smirrorpubsub
  functionName: StorageMirrorSubscriber

  configBucket: ${bucketPrefix}_config
  triggerBucket: ${bucketPrefix}_trigger
  opsBucket: ${bucketPrefix}_operation
  destBucket: ${bucketPrefix}_mirrored
  
  configLocation: config/config.json
  configText: $Cat('$configLocation')



pipeline:


  deploy:
    checkOut:
      action: vc/git:checkout
      Origin:
        URL: https://github.com/viant/smirror.git
      Dest:
        URL: ${appPath}

  set_sdk:
    action: sdk.set
    target: $target
    sdk: go:1.12


    package:
      action: exec:run
      target: $target
      checkError: true
      commands:
        - cd ${appPath}
        - unset GOPATH
        - export GO111MODULE=on
        - rm -rf vendor
        - go mod vendor


    upload:
      action: gcp/cloudfunctions:deploy
      credentials: $gcpCredentials
      '@name': $functionName
      entryPoint: $functionName
      runtime: go111
      availableMemoryMb: 128
      timeout: 540s
      serviceAccountEmail: $serviceAccount
      retry: true
      eventTrigger:
        eventType: google.pubsub.topic.publish
        resource: projects/${gcp.projectID}/topics/$topic
      environmentVariables:
        LOGGING: 'true'
        DEST: gs://${triggerBucket}/
      source:
        URL: ${appPath}/
      sleepTimeMs: 5000
