init:

  '!gcpCredentials': $params.authWith
  serviceAccount: $gcp.ClientEmail
  appPath: /tmp/smirror
  functionName: StorageMirror
  gcp: ${secrets.$gcpCredentials}
  gcpProject: $gcp.ProjectID

  gsbucketPrefix: $Replace($gcpProject,'-','_')

  configBucket: ${bucketPrefix}_config
  triggerBucket: ${bucketPrefix}_trigger
  opsBucket: ${bucketPrefix}_operation
  destBucket: ${bucketPrefix}_mirrored
  
  configLocation: config/config.json
  configText: $Cat('$configLocation')

pipeline:

#  info:
#    action: print
#    init:
#      configJSON: $AsJSON($configText)
#    message: $configJSON
#
#  setup:
#    action: storage:upload
#    init:
#      configJSON: $AsJSON($configText)
#    sourceKey: configJSON
#    expand: true
#    dest:
#      credentials: $gcpCredentials
#      URL: gs://${configBucket}/StorageMirror/config.json


  deploy:
    checkOut:
      action: vc/git:checkout
      origin:
        URL: https://github.com/viant/smirror.git
      dest:
        URL: ${appPath}

    package:
      action: exec:run
      target: $target
      checkError: true
      commands:
        - cd ${appPath}
        - unset GOPATH
        - export GO111MODULE=on
        - rm -rf vendor
        - go mod vendor

    upload:
      action: gcp/cloudfunctions:deploy
      credentials: $gcpCredentials
      '@name': StorageMirror
      entryPoint: StorageMirror
      runtime: go111
      availableMemoryMb: 2048
      timeout: 540s
      serviceAccountEmail: $serviceAccount
      eventTrigger:
        eventType: google.storage.object.finalize
        resource: projects/_/buckets/${triggerBucket}
        failurePolicy:
          retry: {}
      environmentVariables:
        LOGGING: 'true'
        CONFIG: gs://${configBucket}/StorageMirror/config.json
      source:
        URL: ${appPath}/
      sleepTimeMs: 5000
