init:
  '!gcpCredentials': $params.authWith
  gcp: ${secrets.$gcpCredentials}
  gcpProject: $gcp.ProjectID
  slackOAuth: $Cat('$env.HOME/.secret/slack-e2e.json')
  serviceAccount: $gcp.ClientEmail
  prefix: $Replace($gcpProject,'-','_')
  configBucket: ${prefix}_config
  secrets: ${secrets.$awsCredentials}


pipeline:

  deployGCPKey:
    action: gcp/kms:deployKey
    credentials: $gcpCredentials
    ring: ${prefix}_ring
    key: ${prefix}_key
    purpose: ENCRYPT_DECRYPT
    logging: false
    bindings:
      - role: roles/cloudkms.cryptoKeyEncrypterDecrypter
        members:
          - serviceAccount:${gcp.serviceAccount}

  info:
    action: print
    message: $AsString($slackOAuth)

  encryptSlackOAuthToken:
    action: gcp/kms:encrypt
    ring: ${prefix}_ring
    key: ${prefix}_key
    plainData: $AsString($slackOAuth)
    dest:
      URL: gs://${configBucket}/Secrets/slack.json.enc
      credentials: ${gcpCredentials}

