init:
  '!gcpCredentials': $params.authWith
  '!awsCredentials': $params.awsSecrets
  gcp: ${secrets.$gcpCredentials}
  gcpProject: $gcp.ProjectID
  serviceAccount: $gcp.ClientEmail
  configBucket: ${gcpProject}_config
  awsCredentials: aws-e2e
  secrets: ${secrets.$awsCredentials}


pipeline:

  deployGCPKey:
    action: gcp/kms:deployKey
    credentials: $gcpCredentials
    ring: storagemirror_ring
    key: storagemirror
    purpose: ENCRYPT_DECRYPT
    logging: false
    bindings:
      - role: roles/cloudkms.cryptoKeyEncrypterDecrypter
        members:
          - serviceAccount:${gcp.serviceAccount}

  info:
    action: print
    message: $AsString($secrets)

  encryptS3Credentials:
    action: gcp/kms:encrypt
    ring: storagemirror_ring
    key: storagemirror
    plainData: $AsJSON($secrets)
    dest:
      URL: gs://${configBucket}/Secrets/s3-ms.json.enc
      credentials: ${gcpCredentials}
    logging: false
