init:
  part1: $Cat('${parent.path}/data/expect/events_00001.csv')
  part2: $Cat('${parent.path}/data/expect/events_00002.csv')
  events: $Cat('${parent.path}/data/expect/events.json')
  exepct: $AsData($events)

pipeline:

  setupRule:
    action: storage:copy
    expand: true
    source:
      URL: ${parent.path}/rule.json
    dest:
      credentials: $gcpCredentials
      URL: gs://${gsConfigBucket}/StorageMirror/dataflow/case_${parent.index}.json

  trigger:
    action: storage:copy
    sleepTimeMs: 20000
    source:
      URL: ${parent.path}/data/prepare/events.csv
    dest:
      credentials: $gcpCredentials
      URL: gs://${gsTriggerBucket}/data/p6/events.csv

  validate:
    action: msg:pull
    timeoutMs: 10000
    source:
      URL: smirrorSubscription
      type: subscription
      vendor: gcp
      credentials: $gcpCredentials
    count: 2
    expect: $exepct
