init:
  '!awsCredentials': $params.authWith
  bucketPrefix: ms-dataflow
  configBucket: ${bucketPrefix}-config
  triggerBucket: ${bucketPrefix}-trigger
  opsBucket: ${bucketPrefix}-operations

  monitor:
    ConfigURL: s3://${configBucket}/StorageMirror/config.json
    TriggerURL: s3://${triggerBucket}
    ErrorURL:  gs://${opsBucket}/StorageMirror/errors/


pipeline:
  trigger:
    action: aws/lambda:call
    credentials: $awsCredentials
    functionname: StorageMonitor
    payload: $AsJSON($monitor)
