pipeline:

  cleanUp:
    googleStorage:
      action: storage:remove
      assets:
        - URL:  gs://${gsConfigBucket}/StorageMirror
          credentials: $gcpCredentials
        - URL:  gs://${gsConfigBucket}/StorageMirror
          credentials: $awsCredentials
        - URL:  gs://${gsConfigBucket}/StorageMirror/Rules/
          credentials: $gcpCredentials



  deployGoogleStorageMirroConifg:
    action: storage:upload
    sourceKey: mirrorGSConfigJSON
    dest:
      credentials: $gcpCredentials
      URL: gs://${gsConfigBucket}/StorageMirror/config.json

  deployS3MirrorConfig:
    action: storage:upload
    sourceKey: mirrorS3ConfigJSON
    dest:
      credentials: $awsCredentials
      URL: s3://${s3ConfigBucket}/StorageMirror/config.json

  deployS3MirrorCronConfig:
    action: storage:upload
    sourceKey: mirrorS3CronConfigJSON
    dest:
      credentials: $awsCredentials
      URL: s3://${s3ConfigBucket}/StorageMirrorCron/config.json
