pipeline:

  setupMessageBus:
    action: msg:setupResource
    resources:
      - URL: ${gsPrefix}_storage_mirror
        type: topic
        vendor: gcp
        credentials: $gcpCredentials

      - URL: ${gsPrefix}_storage_mirror
        type: subscription
        vendor: gcp
        credentials: $gcpCredentials
        config:
          topic:
            URL: /projects/${gcp.projectID}/topics/${gsPrefix}_storage_mirror

      - URL: $s3Queue
        type: queue
        vendor: aws
        credentials: $awsCredentials

      - URL: ${s3TriggerQueue}
        type: queue
        vendor: aws
        credentials: $awsCredentials
