
pipeline:


  secureWithinGCP:

    deployGCPKey:
      action: gcp/kms:deployKey
      credentials: $gcpCredentials
      ring: ${gsPrefix}_ring
      key: ${gsPrefix}_key
      purpose: ENCRYPT_DECRYPT
      logging: false
      bindings:
        - role: roles/cloudkms.cryptoKeyEncrypterDecrypter
          members:
            - serviceAccount:${gcp.serviceAccount}

    encryptS3Credentials:
      action: gcp/kms:encrypt
      ring: ${gsPrefix}_ring
      key: ${gsPrefix}_key
      plainData: $AsJSON($s3Secrets)
      dest:
        URL: gs://${gsConfigBucket}/Secrets/s3-mirror.json.enc
        credentials: ${gcpCredentials}
      logging: false


  secureWithinAWS:

    deployS3Key:
      credentials: $awsCredentials
      action: aws/kms:setupKey
      aliasName: alias/storagemirror

    deployGSSecret:
      action: aws/ssm:setParameter
      name: storagemirror.gcp
      '@description': Google Storage credentials
      type: SecureString
      keyId: alias/dstransfer
      value: $gcpSecrets.Data

    deployCustomerKey:
      action: aws/ssm:setParameter
      name: storagemirror.customer001CustomKey
      '@description': PartnerX custom encryption key
      type: SecureString
      keyId: alias/storagemirror
      value: $customer001CustomKey


  info:
    action: print
    message: 'encrypted s3 credentials: ${encryptS3Credentials.CipherBase64Text}'
