init:
  defaultContent: 'endly e2e'

pipeline:

  cleanup:
    action: storage:remove
    assets:
      - URL:  gs://${gsDestBucket}/
        credentials: $gcpCredentials
      - URL:  gs://${gsDestBucket}/
        credentials: $awsCredentials
      - URL:  s3://${s3OpsBucket}/
        credentials: $awsCredentials
      - URL:  s3://${s3ExternalBucket}/
        credentials: $awsCredentials
      - URL: 'gs://${gsConfigBucket}/StorageMirror/_.cache'
        credentials: $gcpCredentials
      - URL: 'gs://${gsConfigBucket}/StorageMirror/Rules/'
        credentials: $gcpCredentials
      - URL: 'gs://${s3ConfigBucket}/StorageMirror/_.cache'
        credentials: $awsCredentials
      - URL: 'gs://${s3ConfigBucket}/StorageMirror/Rules/'
        credentials: $awsCredentials


  create3rdParty:
    action: storage:create
    isDir: true
    dest:
      credentials: $awsCredentials
      URL: s3://${s3ExternalBucket}/

  createOnS3:
    config:
      action: storage:create
      isDir: true
      dest:
        credentials: $awsCredentials
        URL: s3://${s3ConfigBucket}/

    ops:
      action: storage:create
      isDir: true
      dest:
        credentials: $awsCredentials
        URL: s3://${s3TriggerBucket}/

    overflow:
      action: storage:upload
      sourceKey: defaultContent
      dest:
        credentials: $awsCredentials
        URL: s3://${s3OverflowBucket}/info

    data:
      action: storage:create
      isDir: true
      dest:
        credentials: $awsCredentials
        URL: s3://${s3OpsBucket}/

    dest:
      action: storage:create
      isDir: true
      dest:
        credentials: $awsCredentials
        URL: s3://${s3DestBucket}/


  createOnGoogleStorage:
    config:
      action: storage:create
      isDir: true
      dest:
        credentials: $gcpCredentials
        URL: s3://${s3ConfigBucket}/


    ops:
      action: storage:create
      isDir: true
      dest:
        credentials: $gcpCredentials
        URL: gs://${gsOpsBucket}/

    data:
      action: storage:create
      isDir: true
      dest:
        credentials: $gcpCredentials
        URL: gs://${gsTriggerBucket}/

    dest:
      action: storage:create
      isDir: true
      dest:
        credentials: $gcpCredentials
        URL: gs://${gsDestBucket}/

