init:

  target:
    URL: ssh://127.0.0.1/
    Credentials: localhost

  gcpCredentials: gcp-e2e
  awsCredentials: aws-e2e

  gcp: ${secrets.$gcpCredentials}
  gcpProject: $gcp.ProjectID

  gsPrefix: $Replace($gcpProject,'-','_')
  gsConfigBucket: ${gsPrefix}_config
  gsTriggerBucket: ${gsPrefix}_trigger
  gsOpsBucket: ${gsPrefix}_operation
  gsDestBucket: ${gsPrefix}_mirrored

  s3bucketPrefix: $Replace($gcpProject,'_','-')
  s3ConfigBucket: ${s3bucketPrefix}-config
  s3TriggerBucket: ${s3bucketPrefix}-trigger
  s3OpsBucket: ${s3bucketPrefix}-operation
  s3DestBucket:  ${s3bucketPrefix}-mirrored
  s3Queue: ${s3bucketPrefix}-queue
  s3TriggerQueue: ${s3bucketPrefix}-trigger-queue
  s3OverflowQueue: ${s3bucketPrefix}-overflow-queue
  s3OverflowBucket: ${s3bucketPrefix}-overflow
  s3ExternalBucket: ${s3bucketPrefix}-external
  customer001CustomKey: this is secret :3rd party phrase


pipeline:

  init:
    system:
      action: run
      request: '@system.yaml'
      tasks: '*'

    app:
      action: run
      request: '@app'
      tasks: '*'

  test:
    action: run
    request: '@regression/regression'
    tasks: '*'

