init:

  gsConfigBucket: viant-e2e-config
  gsTriggerBucket: viant-e2e-storagemirror-inbound
  gsOpsBucket: viant-e2e-ops
  gsDestBucket: viant-e2e-storagemirror-outbound


  s3ConfigBucket: ms-e2e-config
  s3TriggerBucket: ms-e2e-storagemirror-inbound
  s3OpsBucket: ms-e2e-ops
  s3DestBucket: ms-e2e-storagemirror-outbound


  s3ExternalBucket: ms-e2e-storagemirror-ext
  customer001CustomKey: this is secret :3rd party phrase

  gcpCredentials: gcp-e2e
  awsCredentials: aws-e2e
  gcpProject: viant-e2e

pipeline:

  init:
    system:
      action: run
      request: '@system.yaml'
      tasks: '*'

    app:
      action: run
      request: '@app'
      tasks: '*'

  test:
    action: run
    request: '@regression/regression'
    tasks: '*'

