init:


  gcpCredentials: gcp-e2e
  awsCredentials: aws-e2e

  gcp: ${secrets.$gcpCredentials}
  gcpProject: $gcp.ProjectID

  gsbucketPrefix: $Replace($gcpProject,'-','_')
  gsConfigBucket: ${gsbucketPrefix}_config
  gsTriggerBucket: ${gsbucketPrefix}_trigger
  gsOpsBucket: ${gsbucketPrefix}_operations
  gsDestBucket: ${gsbucketPrefix}_mirrored

  s3bucketPrefix: $Replace($gcpProject,'_','-')
  s3ConfigBucket: ${s3bucketPrefix}-config
  s3TriggerBucket: ${s3bucketPrefix}-trigger
  s3OpsBucket: ${s3bucketPrefix}-operations
  s3DestBucket:  ${s3bucketPrefix}-mirrored
  s3Queue: ${s3bucketPrefix}-queue

  s3ExternalBucket: ${s3bucketPrefix}-external
  customer001CustomKey: this is secret :3rd party phrase


pipeline:

  init:
    system:
      action: run
      request: '@system.yaml'
      tasks: '*'

    app:
      action: run
      request: '@app'
      tasks: '*'

  test:
    action: run
    request: '@regression/regression'
    tasks: '*'

