init:
  s3Secrets: ${secrets.$awsCredentials}
  gcpSecrets:  ${secrets.$gcpCredentials}

  mirrorGSConfig: $Cat(config/gs.json)
  mirrorGSConfigJSON: $AsJSON($mirrorGSConfig)

  mirrorS3Config: $Cat(config/s3.json)
  mirrorS3ConfigJSON: $AsJSON($mirrorS3Config)

  mirrorS3CronConfig: $Cat(config/s3Cron.json)
  mirrorS3CronConfigJSON: $AsJSON($mirrorS3CronConfig)


pipeline:

  initStorage:
    action: run
    request: '@system/storage'

  deployConifgs:
    action: run
    request: '@system/config'

  deployResources:
    action: run
    request: '@system/resource'

  deploySecured:
    action: run
    request: '@system/secure'
