pipeline:

  cleanUp:
    action: storage:remove
    sleepTimeMs: 1000
    assets:
      - URL: 'gs://${gsConfigBucket}/StorageMirror/_.cache'
        credentials: $gcpCredentials
      - URL: 'gs://${gsConfigBucket}/StorageMirror/Rules/case_${parent.index}/rule.json'
        credentials: $gcpCredentials


  setupRule:
    action: storage:copy
    expand: true
    source:
      URL: ${parent.path}/rule.json
    dest:
      credentials: $gcpCredentials
      URL: gs://${gsConfigBucket}/StorageMirror/Rules/case_${parent.index}/rule.json


  trigger:
    action: storage:generate
    sleepTimeMs: 95000
    sizeInMb: 270
    dest:
      URL: gs://${gsTriggerBucket}/data/p19/asset.txt
      credentials: $gcpCredentials

  validate:
    action: storage:exists
    assets:
      - URL: s3://${s3DestBucket}/data/p19/asset.txt
        credentials: $awsCredentials

    expect:
      's3://${s3DestBucket}/data/p19/asset.txt': true

