init:
  expect: $Cat('${parent.path}/data/expect/events.json')

pipeline:

  setupRule:
    action: storage:copy
    expand: true
    source:
      URL: ${parent.path}/rule.json
    dest:
      credentials: $gcpCredentials
      URL: gs://${gsConfigBucket}/StorageMirror/Rules/case_${parent.index}.json

  trigger:
    action: storage:copy
    sleepTimeMs: 20000
    source:
      URL: ${parent.path}/data/prepare/
    dest:
      credentials: $gcpCredentials
      URL: gs://${gsTriggerBucket}/data/p14/


  validate:
    action: storage:download
    source:
      URL: gs://${gsDestBucket}/data/p14/events.json
      credentials: $gcpCredentials
    expect: $expect
