pipeline:

  setupRule:
    action: storage:copy
    expand: true
    source:
      URL: ${parent.path}/rule.json
    dest:
      credentials: $awsCredentials
      URL: s3://${s3ConfigBucket}/StorageMirror/dataflow/case_${parent.index}.json


  trigger:
    action: storage:copy
    sleepTimeMs: 20000
    source:
      URL: ${parent.path}/data/prepare/events.csv
    dest:
      credentials: $awsCredentials
      URL: s3://${s3TriggerBucket}/data/p5/events.csv

  validate:
    action: storage:download
    source:
      credentials: $gcpCredentials
      URL: gs://${gsDestBucket}/data/p5/events.csv
    destKey: events
    expect: $Cat('${parent.path}/data/expect/events.csv')
