init:
  gsBucket: e2etst
pipeline:
  secure:
    deployKey:
      action: gcp/kms:deployKey
      credentials: gcp-e2e
      ring: my_ring
      key: my_key
      logging: false
      purpose: ENCRYPT_DECRYPT
      bindings:
        - role: roles/cloudkms.cryptoKeyEncrypterDecrypter
          members:
            - serviceAccount:$gcp.serviceAccount

    keyInfo:
      action: print
      message: 'Deployed Key: ${deployKey.Name}'

    encrypt:
      action: gcp/kms:encrypt
      logging: false
      ring: my_ring
      key: my_key
      source:
        URL: s3-cred.json
      dest:
        credentials: gcp-e2e
        URL: gs://$gsBucket/mirror/config/s3-cred.json.enc
    info:
      action: print
      message: ${encrypt.CipherBase64Text}
