pipeline:

  setupRoute:
    action: storage:copy
    expand: true
    source:
      URL: ${parent.path}/routes.json
    dest:
      credentials: $gcpCredentials
      URL: gs://${gsConifgBucket}/StorageMirror/dataflow/case_${parent.index}.json

  trigger:
    action: storage:copy
    sleepTimeMs: 20000
    source:
      URL: ${parent.path}/data/prepare/events.csv
    dest:
      credentials: $gcpCredentials
      URL: gs://${gsTriggerBucket}/data/p1/events.csv

  validate:
    action: storage:download
    source:
      credentials: $awsCredentials
      URL: s3://${s3DestBucket}/data/p1/events.csv
    destKey: events
    expect: $Cat('${parent.path}/data/expect/events.csv')
