pipeline:

  setupRule:
    action: storage:copy
    expand: true
    source:
      URL: ${parent.path}/rule.json
    dest:
      credentials: $gcpCredentials
      URL: gs://${gsConfigBucket}/StorageMirror/Rules/case_${parent.index}/rule.json

  trigger:
    action: storage:copy
    sleepTimeMs: 20000
    source:
      URL: ${parent.path}/data/prepare/events.csv
    dest:
      credentials: $gcpCredentials
      URL: gs://${gsTriggerBucket}/data/p1/events.csv

  validate:
    action: storage:download
    source:
      credentials: $awsCredentials
      URL: s3://${s3DestBucket}/data/p1/events.csv
    destKey: events
    expect: $Cat('${parent.path}/data/expect/events.csv')
