pipeline:
  trigger:
    action: storage:copy
    sleepTimeMs: 20000
    source:
      URL: ${parent.path}/data/prepare/events.csv
    dest:
      credentials: $gcpCredentials
      URL: gs://${gsBucket}/data/p1/events.csv

  validate:
    action: storage:download
    source:
      credentials: $awsCredentials
      URL: s3://${gsBucket}/data/p1/events.csv
    destKey: events
    expect: $Cat('${parent.path}/data/expect/events.csv')
