init:
  expect: $Cat('${parent.path}/data/expect/events.csv')

pipeline:

  cleanUp:
    action: storage:remove
    sleepTimeMs: 1000
    assets:
      - URL: 'gs://${gsConfigBucket}/StorageMirror/_.cache'
        credentials: $gcpCredentials
      - URL: 'gs://${gsConfigBucket}/StorageMirror/Rules/case_${parent.index}/rule.yaml'
        credentials: $gcpCredentials


  setupRule:
    action: storage:copy
    expand: true
    source:
      URL: ${parent.path}/rule.yaml
    dest:
      credentials: $gcpCredentials
      URL: gs://${gsConfigBucket}/StorageMirror/Rules/case_${parent.index}/rule.yaml


  trigger:
    action: storage:copy
    sleepTimeMs: 20000
    source:
      URL: ${parent.path}/data/prepare/
    dest:
      credentials: $gcpCredentials
      URL: gs://${gsTriggerBucket}/data/p18


  validate:
    action: storage:download
    source:
      URL: gs://${gsDestBucket}/data/p18/events.csv
      credentials: $gcpCredentials
    expect: $expect
