init:
  '!gcpCredentials': $params.authWith
  gcp: ${secrets.$gcpCredentials}
  gcpProject: $gcp.ProjectID
  bucketPrefix: $gcp.ProjectID
  configBucket: ${bucketPrefix}_config
  triggerBucket: ${bucketPrefix}_trigger
  opsBucket: ${bucketPrefix}_operation
  destBucket: ${bucketPrefix}_mirrored

pipeline:
  setupRoute:
    action: storage:copy
    expand: true
    source:
      URL: rule.json
    dest:
      credentials: $gcpCredentials
      URL: gs://${configBucket}/StorageMirror/dataflow/test-rule.json

  trigger:
    action: storage:copy
    source:
      URL: events.csv.gz
    dest:
      credentials: $gcpCredentials
      URL: gs://${triggerBucket}/data/test/events.csv.gz
