init:

  '!awsCredentials': $params.authWith

  functionName: StorageMirror

  handler: smirror
  appPath: /tmp/${handler}
  appLocation: ${appPath}/aws/${handler}.zip
  privilegePolicy: privilege-policy.json
  configLocation: config/config.json
  configText: $Cat('$configLocation')
  bucketPrefix: ms-dataflow
  configBucket: ${bucketPrefix}-config
  triggerBucket: ${bucketPrefix}-trigger
  opsBucket: ${bucketPrefix}-operations


pipeline:

  createBuckets:
    trigger:
      action: storage:create
      isDir: true
      dest:
        credentials: $awsCredentials
        URL: s3://${triggerBucket}/
    ops:
      action: storage:create
      isDir: true
      dest:
        credentials: $awsCredentials
        URL: s3://${opsBucket}/

  uploadConfig:
    action: storage:upload
    init:
      configJSON: $AsJSON($configText)
    sourceKey: configJSON
    expand: true
    dest:
      credentials: $awsCredentials
      URL: s3://${configBucket}/StorageMirror/config.json

  info:
    action: print
    init:
      configJSON: $AsJSON($configText)
    message: $configJSON


  deploy:
    checkOut:
      action: vc/git:checkout
      Origin:
        URL: https://github.com/viant/smirror.git
      Dest:
        URL: ${appPath}

    package:
      action: exec:run
      target: $target
      checkError: true
      commands:
        - unset GOPATH
        - cd ${appPath}
        - export GO111MODULE=on
        - export GOOS=linux
        - export GOARCH=amd64
        - go mod vendor
        - cd aws
        - go build -o $handler
        - zip -j ${handler}.zip $handler

    deployLambda:
      action: aws/lambda:deploy
      credentials: $awsCredentials
      functionname: $functionName
      runtime:  go1.x
      handler: $handler
      timeout: 900
      memorySize: 2048
      environment:
        variables:
          LOGGING: 'true'
          CONFIG: s3://${configBucket}/StorageMirror/config.json
      code:
        zipfile: $LoadBinary(${appLocation})
      rolename: lambda-${functionName}-executor
      define:
        - policyname: lambda-${functionName}-role
          policydocument: $Cat('${privilegePolicy}')
      attach:
        - policyarn: arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  setBucketLambdaNotification:
    action: aws/s3:setupBucketNotification
    bucket: ${triggerBucket}
    lambdaFunctionConfigurations:
      - functionName: $functionName
        id: ObjectCreatedEvents
        events:
          - s3:ObjectCreated:*
        filter:
          prefix:
            - data
