init:

  '!awsCredentials': $params.authWith
  '!gcpCredentials': $params.gcpSecrets
  gcp: ${secrets.$gcpCredentials}
  secret: $gcp.Data


pipeline:
  secure:
    credentials: $awsCredentials
    action: aws/kms:setupKey
    aliasName: alias/storagemirror


  info:
    action: print
    message: 'encrypting: $secret'


  encryptGcpSecrets:
    action: aws/ssm:setParameter
    name: StorrageMirror.GCP.Test
    '@description': Google Storage ${gcp.ProjectID} credentials
    overwrite: true
    type: SecureString
    keyId: alias/storagemirror
    value: $secret


