init:
  gcpCredentials: viant-dataflow
  gsConfigBucket: viant_dataflow_config
  gsTriggerBucket: viant_dataflow_trigger
  gsOpsBucket: viant_dataflow_operation
  gsDestBucket: viant_dataflow_mirrored
  s3DestBucket: ms-e2e-storagemirror-outbound
  gcp: ${secrets.$gcpCredentials}
  gcpProject: $gcp.ProjectID


pipeline:
  setupRoute:
    action: storage:copy
    expand: true
    source:
      URL: rule.json
    dest:
      credentials: $gcpCredentials
      URL: gs://${gsConfigBucket}/StorageMirror/dataflow/test-rule.json

  trigger:
    action: storage:copy
    source:
      URL: events.csv.gz
    dest:
      credentials: $gcpCredentials
      URL: gs://${gsTriggerBucket}/data/test/events.csv.gz
