init:

  '!awsCredentials': $params.authWith
  '!gcpCredentials': $params.gcpSecrets

  gcp: ${secrets.$gcpCredentials}
  gcpProject: $gcp.ProjectID
  prefix: $Replace($gcpProject,'_','-')
  configText: $Cat('config.json')

  handler: smirrorsqs
  appPath: /tmp/${handler}
  appLocation: ${appPath}/aws/sqs/${handler}.zip
  functionName: StorageMirrorSqs
  privilegePolicy: privilege-policy.json
  snsTriggerBucket: ${prefix}-sns-trigger
  triggerBucket: ${prefix}-trigger
  destBucket: ${prefix}-trigger
  configBucket: ${prefix}-config
  sqsTriggerBucket: ${prefix}-sqs-trigger
  queue: ${prefix}-storage-mirror-queue
  dest: s3://${prefix}-trigger
  lambdaConfig: s3://${configBucket}/StorageMirror/sqs_proxy.json

pipeline:

  setupQueue:
    action: msg:setupResource
    credentials: $awsCredentials
    resources:
      - URL: $queue
        type: queue
        vendor: aws

  uploadConfig:
    action: storage:upload
    init:
      configJSON: $AsJSON($configText)
    sourceKey: configJSON
    expand: true
    dest:
      credentials: $awsCredentials
      URL: $lambdaConfig

  deploy:
    checkOut:
      action: vc/git:checkout
      Origin:
        URL: https://github.com/viant/smirror.git
      Dest:
        URL: ${appPath}

    package:
      action: exec:run
      target: $target
      checkError: true
      commands:
        - cd ${appPath}
        - unset GOPATH
        - export GO111MODULE=on
        - export GOOS=linux
        - export GOARCH=amd64
        - go mod vendor
        - cd aws/sqs
        - go build -o ${handler}
        - zip -j ${handler}.zip ${handler}

    deployLambda:
      action: aws/lambda:deploy
      credentials: $awsCredentials
      functionname: $functionName
      runtime:  go1.x
      handler: ${handler}
      timeout: 360
      environment:
        variables:
          CONFIG: $lambdaConfig

      code:
        zipfile: $LoadBinary(${appLocation})
      rolename: lambda-${functionName}-executor
      define:
        - policyname: lambda-${functionName}-role.go
          policydocument: $Cat('${privilegePolicy}')
      attach:
        - policyarn: arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      triggers:
        - source: $queue
          type: sqs
          enabled: true
          batchSize: 1

  setupSqsBucket:
    action: storage:create
    isDir: true
    dest:
      credentials: $awsCredentials
      URL: s3://${triggerBucket}/

  setBucketQueueNotification:
    action: aws/s3:setupBucketNotification
    bucket: ${sqsTriggerBucket}
    queueConfigurations:
      - queue: $queue
        id: ObjectCreatedEvents
        events:
          - s3:ObjectCreated:*
