pipeline:

  init:
    action: storage:remove
    credentials: $awsCredentials
    assets:
      - URL: gs:///${gsBucket}/e2e-mirror/


  test:
    tag: $pathMatch
    description: '@info'
    subPath: 'cases/${index}_*'
    range: 1..006
    template:

      setVars:
        action: nop
        comments: use case init
        skip: $HasResource(${path}/skip.txt)

      test:
        action: run
        request: '@test'
