init:
  expect: $Cat('${parent.path}/data/expect/request.json')
pipeline:

  cleanUp:
    action: storage:remove
    sleepTimeMs: 1000
    assets:
      - URL: 'gs://${gsConfigBucket}/StorageMirror/_.cache'
        credentials: $gcpCredentials
      - URL: 'gs://${gsConfigBucket}/StorageMirror/Rules/case_${parent.index}/rule.yaml'
        credentials: $gcpCredentials
      - URL: 'gs://${gsDestBucket}/data/p023/'
        credentials: $gcpCredentials

  setupRule:
    init:
      parentIndex: ${parent.index}
    action: storage:copy
    expand: true
    source:
      URL: ${parent.path}/rule/
    dest:
      credentials: $gcpCredentials
      URL: gs://${gsConfigBucket}/StorageMirror/Rules/case_${parent.index}/

  trigger:
    action: storage:copy
    sleepTimeMs: 30000
    source:
      URL: ${parent.path}/data/prepare
    dest:
      credentials: $gcpCredentials
      URL: gs://${gsTriggerBucket}/data/p023/


  downloadActual:
    action: storage:download
    source:
      credentials: $gcpCredentials
      URL: 'gs://${gsDestBucket}/data/p023/request.json'
    destKey: actual

  info:
    action: print
    message: $actual

  validate:
    action: validator:assert
    actual: $actual
    expect: $expect

