pipeline:

  setupRoute:
    action: storage:copy
    expand: true
    source:
      URL: ${parent.path}/routes.json
    dest:
      credentials: $gcpCredentials
      URL: gs://${gsConifgBucket}/StorageMirror/dataflow/case_${parent.index}.json


  trigger:
    action: storage:copy
    sleepTimeMs: 20000
    source:
      URL: ${parent.path}/data/prepare/events.csv
    dest:
      credentials: $gcpCredentials
      URL: gs://${gsTriggerBucket}/data/p3/events.csv

  validate:
    chunk1:
      action: storage:download
      source:
        credentials: $awsCredentials
        URL: s3://${s3DestBucket}/data/p3/events_00001.csv
      destKey: events
      expect: $Cat('${parent.path}/data/expect/events_00001.csv')
    chunk2:
      action: storage:download
      source:
        credentials: $awsCredentials
        URL: s3://${s3DestBucket}/data/p3/events_00002.csv
      destKey: events
      expect: $Cat('${parent.path}/data/expect/events_00002.csv')
